// Generated by ts-to-zod
import { z } from "zod";

export const articleApplyTemplatePOSTReqSchema = z.object({
  summary: z.string().optional(),
  content: z.string().optional(),
});

export const articleApplyTemplatePOSTResSchema = z.object({
  success: z.boolean().optional(),
  url: z.string().optional(),
  error: z.string().optional(),
});

export const articleArticleDataGETResSchema = z.object({
  summary: z.string().optional(),
  content: z.string().optional(),
  projectId: z.string().optional(),
  url: z.string().optional(),
  error: z.string().optional(),
});

export const globalAuthorFilterPOSTReqSchema = z.object({
  authorIds: z.array(z.string()),
});

export const globalAuthorFilterPOSTResSchema = z.object({
  authorFilter: z.array(z.string()),
});

export const globalBulkDeleteTemplatesPOSTReqSchema = z.object({
  ids: z.array(z.string()),
});

export const globalBulkDeleteTemplatesPOSTResSchema = z.object({
  success: z.boolean().optional(),
  count: z.number().optional(),
  error: z.string().optional(),
});

export const globalBulkRestoreTemplatesPOSTReqSchema = z.object({
  ids: z.array(z.string()),
});

export const globalBulkRestoreTemplatesPOSTResSchema = z.object({
  success: z.boolean().optional(),
  count: z.number().optional(),
  error: z.string().optional(),
});

export const globalCreateDraftPOSTResSchema = z.object({
  id: z.string().optional(),
  url: z.string().optional(),
  error: z.string().optional(),
});

export const globalDeletedTemplatesGETReqSchema = z.object({
  projects: z.string().optional(),
});

export const globalImportPredefinedTemplatesPOSTResSchema = z.object({
  success: z.boolean().optional(),
  importedCount: z.number().optional(),
  error: z.string().optional(),
});

export const globalPermanentTemplateDELETEReqSchema = z.object({
  id: z.string().optional(),
});

export const globalPermanentTemplateDELETEResSchema = z.object({
  success: z.boolean().optional(),
  error: z.string().optional(),
});

export const globalProjectFilterPOSTResSchema = z.object({
  projectFilter: z.array(z.string()),
});

export const globalRestoreTemplatePOSTReqSchema = z.object({
  id: z.string(),
});

export const globalSettingsGETResSchema = z.object({
  purgeIntervalDays: z.number(),
});

export const globalTemplateUsagePOSTReqSchema = z.object({
  id: z.string(),
});

export const globalTemplateUsagePOSTResSchema = z.object({
  success: z.boolean().optional(),
  error: z.string().optional(),
});

export const globalTemplatesDELETEReqSchema = z.object({
  id: z.string().optional(),
});

export const globalTemplatesDELETEResSchema = z.object({
  success: z.boolean().optional(),
  error: z.string().optional(),
});

export const globalTemplatesGETReqSchema = z.object({
  projects: z.string().optional(),
});

export const globalToggleFavoritePOSTReqSchema = z.object({
  id: z.string(),
});

export const globalToggleFavoritePOSTResSchema = z.object({
  favorites: z.array(z.string()).optional(),
  error: z.string().optional(),
});

export const globalToggleShowFavoritesPOSTResSchema = z.object({
  showFavoritesOnly: z.boolean(),
});

export const globalUserPreferencesGETResSchema = z.object({
  favorites: z.array(z.string()),
  showFavoritesOnly: z.boolean(),
  authorFilter: z.array(z.string()),
  projectFilter: z.array(z.string()),
});

export const templateAuthorSchema = z.object({
  id: z.string().optional(),
  login: z.string().optional(),
  fullName: z.string().optional(),
});

export const templateSchema = z.object({
  id: z.string(),
  name: z.string(),
  summary: z.string(),
  content: z.string(),
  createdAt: z.number().optional(),
  usageCount: z.number().optional(),
  isPrivate: z.boolean().optional(),
  deletedAt: z.number().optional(),
  author: templateAuthorSchema.optional(),
  lockedForOthers: z.boolean().optional(),
  projectId: z.string().optional(),
  projectName: z.string().optional(),
  canEdit: z.boolean().optional(),
});

export const globalRestoreTemplatePOSTResSchema = z.object({
  template: templateSchema.optional(),
  error: z.string().optional(),
});

export const globalTemplatesGETResSchema = z.object({
  templates: z.array(templateSchema),
});

export const globalTemplatesPOSTResSchema = z.object({
  template: templateSchema.optional(),
  error: z.string().optional(),
});

export const globalDeletedTemplatesGETResSchema = z.object({
  templates: z.array(templateSchema),
});

// Nested schema object for validation system
export const schema = {
  article: {
    'apply-template': {
      POST: {
        Req: articleApplyTemplatePOSTReqSchema,
        Res: articleApplyTemplatePOSTResSchema
      }
    },
    'article-data': {
      GET: {
        Res: articleArticleDataGETResSchema
      }
    }
  },
  global: {
    'author-filter': {
      POST: {
        Req: globalAuthorFilterPOSTReqSchema,
        Res: globalAuthorFilterPOSTResSchema
      }
    },
    'bulk-delete-templates': {
      POST: {
        Req: globalBulkDeleteTemplatesPOSTReqSchema,
        Res: globalBulkDeleteTemplatesPOSTResSchema
      }
    },
    'bulk-restore-templates': {
      POST: {
        Req: globalBulkRestoreTemplatesPOSTReqSchema,
        Res: globalBulkRestoreTemplatesPOSTResSchema
      }
    },
    'create-draft': {
      POST: {
        Req: globalCreateDraftPOSTReqSchema,
        Res: globalCreateDraftPOSTResSchema
      }
    },
    'deleted-templates': {
      GET: {
        Req: globalDeletedTemplatesGETReqSchema,
        Res: globalDeletedTemplatesGETResSchema
      }
    },
    'import-predefined-templates': {
      POST: {
        Req: globalImportPredefinedTemplatesPOSTReqSchema,
        Res: globalImportPredefinedTemplatesPOSTResSchema
      }
    },
    'permanent-template': {
      DELETE: {
        Req: globalPermanentTemplateDELETEReqSchema,
        Res: globalPermanentTemplateDELETEResSchema
      }
    },
    'project-filter': {
      POST: {
        Req: globalProjectFilterPOSTReqSchema,
        Res: globalProjectFilterPOSTResSchema
      }
    },
    'restore-template': {
      POST: {
        Req: globalRestoreTemplatePOSTReqSchema,
        Res: globalRestoreTemplatePOSTResSchema
      }
    },
    settings: {
      GET: {
        Res: globalSettingsGETResSchema
      }
    },
    'template-usage': {
      POST: {
        Req: globalTemplateUsagePOSTReqSchema,
        Res: globalTemplateUsagePOSTResSchema
      }
    },
    templates: {
      DELETE: {
        Req: globalTemplatesDELETEReqSchema,
        Res: globalTemplatesDELETEResSchema
      },
      GET: {
        Req: globalTemplatesGETReqSchema,
        Res: globalTemplatesGETResSchema
      },
      POST: {
        Req: globalTemplatesPOSTReqSchema,
        Res: globalTemplatesPOSTResSchema
      }
    },
    'toggle-favorite': {
      POST: {
        Req: globalToggleFavoritePOSTReqSchema,
        Res: globalToggleFavoritePOSTResSchema
      }
    },
    'toggle-show-favorites': {
      POST: {
        Req: globalToggleShowFavoritesPOSTReqSchema,
        Res: globalToggleShowFavoritesPOSTResSchema
      }
    },
    'user-preferences': {
      GET: {
        Res: globalUserPreferencesGETResSchema
      }
    }
  }
};
