/**
 * App Settings - Auto-generated types for app settings and extension properties
 * 
 * This file is automatically generated by the youtrack-app-settings Vite plugin.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 * 
 * Generated from:
 * - src/settings.json (app settings)
 * - entity-extensions.json (extension properties)
 * 
 * These types are declared globally and automatically picked up by all handler contexts.
 * 
 * @generated
 */

declare global {
  /**
   * App settings type from settings.json
   * Automatically accessible via ctx.settings in all handlers
   */
  type AppSettings = {
  
    /** Number of days to keep deleted templates in the trash before permanent deletion. 7 by default. */
    purgeIntervalDays?: number;
  };
  
  /**
   * Issue extension properties type from entity-extensions.json
   * Automatically accessible via issue.extensionProperties when using ExtendedIssue
   */
  type IssueExtensionProperties = Record<string, never>;
  
  /**
   * Project extension properties type from entity-extensions.json
   * Automatically accessible via project.extensionProperties when using ExtendedProject
   */
  type ProjectExtensionProperties = Record<string, never>;
  
  /**
   * Article extension properties type from entity-extensions.json
   * Automatically accessible via article.extensionProperties when using ExtendedArticle
   */
  type ArticleExtensionProperties = Record<string, never>;
  
  /**
   * User extension properties type from entity-extensions.json
   * Automatically accessible via user.extensionProperties when using ExtendedUser
   */
  type UserExtensionProperties = {
      templates?: string;
      deletedTemplates?: string;
      favorites?: string;
      showFavoritesOnly?: string;
      authorFilter?: string;
      projectFilter?: string;
    };
  
  /**
   * AppGlobalStorage extension properties type from entity-extensions.json
   * Automatically accessible via ctx.globalStorage.extensionProperties
   */
  type AppGlobalStorageExtensionProperties = {
      templates?: string;
      deletedTemplates?: string;
      initialImportDone?: string;
    };
}

// This is needed to make the file a module
export {};
